baseURL = 'https://Oranges1994.github.io/'
#languageCode = 'en-us'
title = "fanbubu's home"
theme = 'tokiwa'


DefaultContentLanguage = "en"
author = "He Yeshuang"
copyright = "Copyright © 2023–2023"
disqusShortname = "YOURSHORTNAME"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-FAKE" ## or "G-xxxxxxxx" in Google Analytics v4, in hugo v0.82+
hasCJKLanguage = true
languageCode = "cn"

[markup]
[markup.highlight]
style = "monokailight"

[markup.goldmark.renderer]
unsafe = true

[params]
bannerFont = "fonts/Thanks-Lovely.woff" 
#bannerFont = "fonts/exampleFont" 
description = """
For Grace Ma, who used full food to explain what is called hot love in the second anniversary.
""" 
env = "production" # for Google Analytics and DISQUS.
favicon = "img/favicon-32x32.png" 
fuse = true # for searchbox. "JSON" must added to output contents. See [outputs].
math = true # for introducing $KaTEX$
useChineseFonts = true 
postDateFormat = "2006-1-2"

[menu]
# Shown in the side menu.
[[menu.main]]
identifier = "post"
name = "Posts"
url = "/post/"
weight = 1
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
[social]
bilibili = "https://space.bilibili.com/35482419?spm_id_from=333.337.0.0"
github = "https://github.com/Oranges1994/"
#gitlab = "http://gitlab.com/"
#instagram = "http://example.com/"
#mail = "mailto:anon@example.com"
#twitter = "http://twitter.com/"
#weibo = "http://example.com/"
#youtube = "http://youtube.com/"
#zhihu = "http://example.com/"
# any icon in layouts/partials/svg can be used by the name without the "-line.svg"

[outputs]
home = ["HTML", "RSS", "JSON"]